const router = require('express').Router();
const db = require('../config/database');
const { authenticate } = require('../middleware/auth');
const { requireRole } = require('../middleware/role');
const walletService = require('../services/walletService');
const notificationService = require('../services/notificationService');

function getConfig(key) {
  const row = db.prepare('SELECT value FROM app_config WHERE key = ?').get(key);
  return row ? row.value : null;
}

function generateUniqueCode() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let code, attempts = 0;
  do {
    code = 'HK';
    for (let i = 0; i < 6; i++) code += chars[Math.floor(Math.random() * chars.length)];
    attempts++;
  } while (db.prepare('SELECT id FROM referral_coupons WHERE code = ?').get(code) && attempts < 30);
  return code;
}

router.use(authenticate);

// GET /api/referral/my-codes — list all codes generated by me (unused + used)
router.get('/my-codes', requireRole('customer'), (req, res) => {
  const signupCredit   = parseFloat(getConfig('referral_signup_credit') || '0');
  const firstOrderBonus = parseFloat(getConfig('referral_first_order_bonus') || '0');
  const enabled = getConfig('referral_enabled') !== '0';

  const codes = db.prepare(`
    SELECT rc.*, u.name as used_by_name
    FROM referral_coupons rc
    LEFT JOIN users u ON u.id = rc.used_by_user_id
    WHERE rc.owner_user_id = ?
    ORDER BY rc.created_at DESC
  `).all(req.user.id);

  const unusedCount  = codes.filter(c => !c.used_by_user_id).length;
  const usedCount    = codes.filter(c => c.used_by_user_id).length;
  const pendingBonus = codes.filter(c => c.used_by_user_id && !c.bonus_credited_at).length;

  // Can this customer still apply a referral code from someone else?
  const alreadyApplied = !!db.prepare('SELECT id FROM referral_coupons WHERE used_by_user_id = ?').get(req.user.id);
  const priorOrders = db.prepare("SELECT COUNT(*) as c FROM orders WHERE user_id = ? AND status != 'cancelled'").get(req.user.id).c;
  // Show the apply section if no code used yet — backend enforces the order restriction on apply
  const canApply = !alreadyApplied;

  res.json({ codes, unused_count: unusedCount, used_count: usedCount,
    pending_bonus_count: pendingBonus, signup_credit: signupCredit,
    first_order_bonus: firstOrderBonus, enabled, can_apply: canApply });
});

// POST /api/referral/generate — generate a new invite code for a specific phone
router.post('/generate', requireRole('customer'), (req, res) => {
  if (getConfig('referral_enabled') === '0') {
    return res.status(400).json({ error: 'Referral program is currently disabled' });
  }
  const { phone } = req.body;
  if (!phone || !/^[0-9]{10}$/.test(phone.trim())) {
    return res.status(400).json({ error: 'Enter the 10-digit phone number of the friend you want to invite' });
  }
  const invitedPhone = phone.trim();

  // Can't invite yourself
  if (invitedPhone === req.user.phone) {
    return res.status(400).json({ error: 'You cannot invite yourself' });
  }

  // Can't invite someone who is already a registered customer
  const existing = db.prepare("SELECT id FROM users WHERE phone = ? AND role = 'customer'").get(invitedPhone);
  if (existing) return res.status(400).json({ error: 'This number is already registered on HappyKrishi' });

  // Can't generate a second invite for the same phone
  const duplicate = db.prepare('SELECT id FROM referral_coupons WHERE invited_phone = ? AND owner_user_id = ?').get(invitedPhone, req.user.id);
  if (duplicate) return res.status(400).json({ error: 'You have already sent an invite to this number' });

  const code = generateUniqueCode();
  db.prepare(
    "INSERT INTO referral_coupons (code, owner_user_id, invited_phone) VALUES (?,?,?)"
  ).run(code, req.user.id, invitedPhone);
  res.status(201).json({ code, invited_phone: invitedPhone });
});

// POST /api/referral/apply — apply someone else's code
router.post('/apply', requireRole('customer'), (req, res) => {
  const { code } = req.body;
  if (!code || !code.trim()) return res.status(400).json({ error: 'code is required' });

  if (getConfig('referral_enabled') === '0') {
    return res.status(400).json({ error: 'Referral program is currently disabled' });
  }

  const trimmedCode = code.trim().toUpperCase();

  // Find the code in referral_coupons (unused)
  const coupon = db.prepare(`
    SELECT rc.*, u.name as owner_name
    FROM referral_coupons rc
    JOIN users u ON u.id = rc.owner_user_id
    WHERE rc.code = ?
  `).get(trimmedCode);

  if (!coupon) return res.status(404).json({ error: 'Invalid referral code' });
  if (coupon.owner_user_id === req.user.id) return res.status(400).json({ error: 'You cannot use your own referral code' });

  // Generic code — multi-use
  if (coupon.is_generic) {
    if (coupon.max_uses && coupon.use_count >= coupon.max_uses) {
      return res.status(400).json({ error: 'This referral code has reached its maximum uses' });
    }
    // Each customer can only use one referral code total
    const alreadyUsed = db.prepare('SELECT id FROM referral_coupons WHERE used_by_user_id = ?').get(req.user.id);
    if (alreadyUsed) return res.status(400).json({ error: 'You have already used a referral code' });
    const priorOrders = db.prepare("SELECT COUNT(*) as c FROM orders WHERE user_id = ? AND status != 'cancelled'").get(req.user.id).c;
    if (priorOrders > 0) return res.status(400).json({ error: 'Referral codes can only be applied before your first order' });

    // Use custom credit if set on this generic code, else fall back to global config
    const signupCredit = coupon.custom_signup_credit != null
      ? parseFloat(coupon.custom_signup_credit)
      : parseFloat(getConfig('referral_signup_credit') || '0');
    const firstOrderBonus = parseFloat(getConfig('referral_first_order_bonus') || '0');

    // Record usage — for generic codes we don't set used_by_user_id on the coupon row
    // (that would mark it "used"); instead we create a usage record by incrementing use_count
    // and storing this customer's relationship via a new row in referral_coupons
    // SIMPLER: track each usage by creating a child row pointing to the generic coupon
    const usageRow = db.prepare(`
      INSERT INTO referral_coupons (code, owner_user_id, used_by_user_id, used_at, signup_credit_amount, is_generic)
      VALUES (?, ?, ?, datetime('now'), ?, 0)
    `).run(coupon.code + '_USE_' + req.user.id, coupon.owner_user_id, req.user.id, signupCredit > 0 ? signupCredit : null);

    db.prepare('UPDATE referral_coupons SET use_count = use_count + 1 WHERE id = ?').run(coupon.id);

    if (signupCredit > 0) {
      walletService.credit(req.user.id, signupCredit, 'credit', 'referral_signup', coupon.id,
        `Referral sign-up bonus (code: ${coupon.code})`);
      notificationService.sendToUser(req.user.id, 'Referral Bonus Added! 🎉',
        `₹${signupCredit} added to your wallet for using referral code ${coupon.code}.`);
    }
    return res.json({
      message: signupCredit > 0 ? `₹${signupCredit} added to your wallet!` : 'Referral code applied!',
      signup_credit: signupCredit,
      first_order_bonus_info: firstOrderBonus > 0
        ? `Place your first order to help the referrer earn ₹${firstOrderBonus}`
        : null,
    });
  }

  // Personal code (original logic)
  if (coupon.used_by_user_id) return res.status(400).json({ error: 'This code has already been used' });

  // If the code was generated for a specific phone, only that phone can use it
  if (coupon.invited_phone && coupon.invited_phone !== req.user.phone) {
    return res.status(400).json({ error: 'This code was generated for a different phone number' });
  }

  // Each customer can only benefit from one referral code
  const alreadyUsed = db.prepare('SELECT id FROM referral_coupons WHERE used_by_user_id = ?').get(req.user.id);
  if (alreadyUsed) return res.status(400).json({ error: 'You have already used a referral code' });

  // Only new customers (no prior orders) can apply a referral code
  const priorOrders = db.prepare("SELECT COUNT(*) as c FROM orders WHERE user_id = ? AND status != 'cancelled'").get(req.user.id).c;
  if (priorOrders > 0) return res.status(400).json({ error: 'Referral codes can only be applied by new customers before their first order' });

  const signupCredit    = parseFloat(getConfig('referral_signup_credit') || '0');
  const firstOrderBonus = parseFloat(getConfig('referral_first_order_bonus') || '0');

  // Mark code as used
  db.prepare(`
    UPDATE referral_coupons
    SET used_by_user_id=?, used_at=datetime('now'), signup_credit_amount=?
    WHERE id=?
  `).run(req.user.id, signupCredit > 0 ? signupCredit : null, coupon.id);

  // Credit signup bonus immediately
  if (signupCredit > 0) {
    walletService.credit(req.user.id, signupCredit, 'credit', 'referral_signup', coupon.id,
      `Referral sign-up bonus from ${coupon.owner_name}'s invite`);
    notificationService.sendToUser(req.user.id, 'Referral Bonus Added! 🎉',
      `₹${signupCredit} added to your wallet for using ${coupon.owner_name}'s referral code.`);
    notificationService.sendToUser(coupon.owner_user_id, 'Someone Used Your Referral! 🎉',
      `A new customer used your invite code. You'll earn ₹${firstOrderBonus} when they place their first order.`);
  }

  res.json({
    message: `₹${signupCredit} added to your wallet!`,
    signup_credit: signupCredit,
    first_order_bonus_info: `Place your first order to earn the referrer ₹${firstOrderBonus}`,
  });
});

module.exports = router;
